Ignore .cache directory when running jest (#193)
In some instances, tests fail due to Jest trying to run test files contained in the `.cached` directory.

Log:

```
 FAIL  packages/app-icon-explorer/.cache/__tests__/error-overlay-handler.js
  ● Test suite failed to run

    /Users/kaelig/src/github.com/Shopify/polaris-icons/packages/app-icon-explorer/.cache/__tests__/error-overlay-handler.js:9
    import "@babel/polyfill";
           ^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)

 FAIL  packages/app-icon-explorer/.cache/__tests__/find-page.js
  ● Test suite failed to run

    Jest encountered an unexpected token
```

... and so on.